name: tdclient_dart
description: WebSocket and HTTP client for Tada API to write network code faster.
homepage: https://github.com/tada-team/tdclient_dart
repository: https://github.com/tada-team/tdclient_dart
issue_tracker: https://github.com/tada-team/tdclient_dart/issues

version: 1.0.0-dev
environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  # Code generation.
  json_annotation: ^3.1.1
  freezed_annotation: ^0.12.0

  # Network.
  dio: ^3.0.10
  tdproto_dart: ^1.0.1-dev
  cookie_jar: ^1.0.1

  # Infrastructure.
  logger: ^0.9.4
  dart_extensions: ^1.0.2

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: any
  json_serializable: ^3.5.1
  freezed: ^0.12.6
