name: tdclient_dart
description: WebSocket and HTTP client for Tada API to write network code faster.
homepage: https://github.com/tada-team/tdclient_dart
repository: https://github.com/tada-team/tdclient_dart
issue_tracker: https://github.com/tada-team/tdclient_dart/issues

version: 1.0.1-dev
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Code generation.
  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.1

  # Network.
  dio: ^4.0.0-prev3
  tdproto_dart:
    git:
      url: git@github.com:tada-team/tdproto_dart.git
      ref: ead584eab3f1b357d6aa8dec51a6e042c93e5eb9

  cookie_jar: ^3.0.0-beta2
  dio_cookie_manager: ^2.0.0-prev1
  web_socket_channel: ^2.0.0

  # Utils.
  logger: ^1.0.0

dev_dependencies:
  # Code style.
  pedantic: ^1.9.0

  # Code generation.
  build_runner: ^1.12.2
  json_serializable: ^4.0.3
  freezed: ^0.14.1

dependency_overrides:
  # Remove these overrides when freezed is updated to build 2.0.0
  # region
  build: ^2.0.0
  build_resolvers: ^2.0.0
  source_gen: ^1.0.0
  # endregion

  # Remove this override when build_runner is updated to web_socket_channel 2.0.0
  web_socket_channel: ^2.0.0
